// ROOT
export const LOGGING_ADMIN = "LOGGING_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

// ADMIN - DISHES
export const FETCH_DISHES_BEGIN = "FETCH_DISHES_BEGIN";
export const FETCH_DISHES_SUCCESS = "FETCH_DISHES_SUCCESS";
export const FETCH_DISHES_FAILURE = "FETCH_DISHES_FAILURE";
export const CLEAR_DISHES = "CLEAR_DISHES";

export const SET_ACTIVE_DISH = "SET_ACTIVE_DISH";
export const ADD_DISH = "ADD_DISH";
export const DELETE_DISH = "DELETE_DISH";
export const MODIFY_DISH = "MODIFY_DISH";
export const UPDATE_FILTER_DISHES = "UPDATE FILTER DISHES";
export const UPDATE_CHECKED_DISHES = "UPDATE_CHECKED_DISHES";
export const CHECKED_ALL_DISHES = "CHECKED_ALL_DISHES";
export const UNCHECKED_ALL_DISHES = "UNCHECKED_ALL_DISHES";
