spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/apps/ravintola/db-file
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
server:
  port: ${PORT:8080}

security.enable-csrf: false


